
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: root
  host: 172.17.0.1
  port: 3307
  #socket: /tmp/mysql.sock

development:
  <<: *default
  database: rubycoffe_dev

test:
  <<: *default
  database: rubycoffe_test

production:
  <<: *default
  database: rubycoffe_production
